name = "map-search"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration for static hosting
[pages]
pages_build_output_dir = "./out"

# Environment variables (if needed)
[vars]
ENVIRONMENT = "production"
