name = "map-nextjs"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:cloudflare"
output_dir = "out"

[site]
bucket = "out"

[env.production]
name = "map-nextjs-production"

[env.staging]
name = "map-nextjs-staging"
